JesparWebApplication/JesparWebApplication/Models/PurchaseViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jespar.Model.Model;
using System.ComponentModel.DataAnnotations;


namespace JesparWebApplication.Models
{
    public class PurchaseViewModel
    {
        
        public int Id { set; get; }

       
        public DateTime Date { set; get; }
        public string InvoiceNo { set; get; }

        public string SupplierName { set; get; }
        public int SupplierId { set; get; }
        public Supplier Supplier { set; get; }

        //for create table 
        public List<Purchase> Purchases { set; get; }

        



        //-------------------------------


        public string Code { set; get; }

        [DataType(DataType.Date)]
        public DateTime ManuFractureDateTime { set; get; }

        [DataType(DataType.Date)]
        public DateTime ExpireDateTime { set; get; }
        public string Remarks { set; get; }
        public int Quantity { set; get; }
        public int UnitPrice { set; get; }
        public int TotalPrice { set; get; }
        public int MRP { set; get; }

        public int ProductId { set; get; }
        public Product Product { set; get; }
        public int PurchaseId { set; get; }
        public Purchase Purchase { set; get; }

        public List<PurchaseDetails> PurchaseDetailses { set; get; }
        //----------------------------------------
        public List<SelectListItem> SupplierSelectListItems { set; get; }
        public List<SelectListItem> ProductSelectListItems { set; get; }

        public int CategoryId { set; get; }
        public Category Category { set; get; }
        public List<SelectListItem> CategorySelectListItems { set; get; }



    }

}

JesparWebApplication/JesparWebApplication/Controllers/PurchaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JesparWebApplication.Models;
using Jespar.BLL.BLL;
using Jespar.Model.Model;
using AutoMapper;

namespace JesparWebApplication.Controllers
{

    public class PurchaseController : Controller
    {

        SupplierManager _supplierManager = new SupplierManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        PurchaseManager _purchaseManager = new PurchaseManager();

        [HttpGet]
        public ActionResult AddPurchase()
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.SupplierSelectListItems = _supplierManager.GetAll().Select(c => new SelectListItem
                                                                                    {
                                                                                        Value = c.Id.ToString(),
                                                                                        Text = c.Name
                                                                                    }).ToList();


            purchaseViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
                                                                                    {
                                                                                        Value = c.Id.ToString(),
                                                                                        Text = c.Name
                                                                                    }).ToList();

            ViewBag.Category = purchaseViewModel.CategorySelectListItems;

            

            //purchaseViewModel.ProductSelectListItems = _productManager.GetAll().Select(c => new SelectListItem
            //                                                                        {
            //                                                                            Value = c.Id.ToString(),
            //                                                                            Text = c.Name
            //                                                                        }).ToList();

            //if(purchaseViewModel.ProductSelectListItems)


            return View(purchaseViewModel);
        }

        public JsonResult GetSupplierNameBySupplierId(int supplierId)
        {
            var supplierList = _supplierManager.GetAll().Where(c => c.Id == supplierId).ToList();
            var supplier = from s in supplierList select (s.Name);
            return Json(supplier, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductByCategoryId(int categoryId)
        {
            var productList = _productManager.GetAll().Where(c => c.CategoryId == categoryId).ToList();
            var products = from p in productList select (new { p.Id, p.Name});
            return Json(products, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductCodeByProductId(int productId)
        {
            var productList = _productManager.GetAll().Where(c => c.Id == productId).ToList();
            var productCode = from p in productList select (new { p.Code, p.Name});
            return Json(productCode, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPreviousProductPurchaseInfoByCode(int productId)
        {
            var purchaseProductCodeList = _purchaseManager.GetAll().Where(c => c.ProductId == productId).ToList();
            var purchaseProductCode = from p in purchaseProductCodeList select (new { p.UnitPrice, p.MRP});
            return Json(purchaseProductCode, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPurchaseAvailableQuantity(int productId)
        {
            var purchaseProductCodeList = _purchaseManager.GetAll().Where(c => c.ProductId == productId).ToList();
            var availableQuantity = (from p in purchaseProductCodeList  select p.Quantity).Sum();
            return Json(availableQuantity, JsonRequestBehavior.AllowGet);
            //return availableQuantity;
        }

        [HttpPost]
        public ActionResult AddPurchase(PurchaseViewModel purchaseViewModel)
        {
            purchaseViewModel.SupplierSelectListItems = _supplierManager.GetAll().Select(c => new SelectListItem
                                                                                    {
                                                                                        Value = c.Id.ToString(),
                                                                                        Text = c.Name
                                                                                    }).ToList();


            purchaseViewModel.CategorySelectListItems = _categoryManager.GetAll().Select(c => new SelectListItem
                                                                                    {
                                                                                        Value = c.Id.ToString(),
                                                                                        Text = c.Name
                                                                                    }).ToList();

            ViewBag.Category = purchaseViewModel.CategorySelectListItems;

            //purchaseViewModel.ProductSelectListItems = _productManager.GetAll().Select(c => new SelectListItem
            //                                                                        {
            //                                                                            Value = c.Id.ToString(),
            //                                                                            Text = c.Name
            //                                                                        }).ToList();




            string message = "";
            Purchase purchase = Mapper.Map<Purchase>(purchaseViewModel);
            if (_purchaseManager.Add(purchase))
            {
                message = "Data Save Successfully";
            }
            else
            {
                message = "not save";
            }

            ViewBag.Message = message;

            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();

            return View(purchaseViewModel);
        }

        [HttpGet]
        public ActionResult PurchaseInfo()
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();
            return View(purchaseViewModel);
        }
        [HttpPost]
        public ActionResult PurchaseInfo(PurchaseViewModel purchaseViewModel)
        {
            //PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.Purchases = _purchaseManager.GetPurchaseReportAll();
            return View(purchaseViewModel);
        }

        [HttpGet]
        public ActionResult PurchaseDetails(int id)
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll().Where(c => c.PurchaseId == id).ToList();
            return View(purchaseViewModel);
        }
        [HttpPost]
        public ActionResult PurchaseDetails(PurchaseViewModel purchaseViewModel)
        {
            
            purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll();
            return View(purchaseViewModel);
        }
        public ActionResult GetPurchaseDetailsByPurchaseId(int purchaseId)
        {
            PurchaseViewModel purchaseViewModel = new PurchaseViewModel();
            purchaseViewModel.PurchaseDetailses = _purchaseManager.GetAll().Where(c => c.PurchaseId == purchaseId).ToList();
            return PartialView("Purchase/_purchaseReport", purchaseViewModel);
        }
    }
}

JesparWebApplication/JesparWebApplication/Views/Purchase/PurchaseDetails.cshtml
@model JesparWebApplication.Models.PurchaseViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

    <div class="card">
        <div class="grid-header">
            <div class="row">
                <label class="col-md-10">Purchase Report</label>

            </div>

        </div>

        <div class="card-body">
            <table class="table table-bordered">
                <thead class="thead-dark">
                    <tr>
                        <th>SL</th>
                        <th>Code</th>
                        <th>ManufractureDate</th>
                        <th>ExpireDate</th>
                        <th>Quantity</th>
                        <th>Unit Price</th>
                        <th>MRP</th>
                        <th>TotalMrp</th>

                    </tr>
                </thead>
                <tbody>
                    @{ int i = 1;}
                    @foreach (var purchase in Model.PurchaseDetailses)
                    {
                        <tr>
                            <td>@(i++)</td>
                            <td>@purchase.Code</td>
                            <td>@purchase.ManuFractureDateTime</td>
                            <td>@purchase.ExpireDateTime</td>
                            <td>@purchase.Quantity</td>
                            <td>@purchase.UnitPrice</td>
                            <td>@purchase.MRP</td>
                            <td>@purchase.TotalPrice</td>
                        

                        
                        </tr>
                    }


                </tbody>
            </table>
        </div>

    </div>

JesparWebApplication/JesparWebApplication/Views/Purchase/PurchaseInfo.cshtml
@model JesparWebApplication.Models.PurchaseViewModel
@{

    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <div class="container">

        <div class="card">
            <div class="grid-header">
                <div class="row">
                    <label class="col-md-10">Purchase Report</label>

                </div>

            </div>

            <div class="card-body">
                <table class="table table-bordered">
                    <thead class="thead-dark">
                        <tr>
                            <th>SL</th>
                            <th>Supplier Name</th>
                            <th>Invoice Number</th>
                            <th>Date</th>
                            <th>Details</th>

                        </tr>
                    </thead>
                    <tbody>
                            @{ int i = 1;}
                            @foreach (var purchase in Model.Purchases)
                            {
                            <tr>
                                <td>@(i++)</td>
                                <td>@purchase.SupplierName</td>
                                <td>@purchase.InvoiceNo</td>
                                <td>@purchase.Date</td>



                                <td>
                                    @Html.ActionLink("Detalis", "PurchaseDetails", "Purchase", new { Id = purchase.Id }, null)
                               
                                </td>
                                @*<td style='visibility:hidden' id="purchaseId">@purchase.Id</td>*@
                            </tr>
                        }


                    </tbody>
                </table>
            </div>
            <div class="row">
                @*<div class="col-md-12" id="studentPartial"></div>*@
                @*<a href="~/Views/Shared/Student/_StudentDetails.cshtml"id="partial"> </a>*@
            </div>

        </div>

        @*@{
            Html.RenderPartial("~/Views/Shared/Purchase/_purchaseReport.cshtml", Model);
        }*@
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#partial").click(function () {
            var purchaseId = $("#purchaseId").val();
            var jsonrequestData = { PurchaseId: purchaseId };
            $.ajax({
                url: "/Purchase/GetPurchaseDetailsByPurchaseId",
                type: "POST",
                data: jsonrequestData,
                success: function (data) {

                    $("#partial").html(data);
                },
                error: function () {
                    alert("not done");
                }
            });
        });
    });
    </script>