JesparWebApplication/JesparWebApplication/Models/SupplierViewModel.cs
using Jespar.Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace JesparWebApplication.Models
{
    public class SupplierViewModel
    {
        public int Id { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]
        [MaxLength(4, ErrorMessage = "Code Length Must be in 4!!")]
        [MinLength(4, ErrorMessage = "Code Length Must be in 4!!")]
        [Display(Name = "Code: ")]

        public string Code { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]
        [Display(Name = "Name: ")]
        public string Name { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]
        [Display(Name = "Address: ")]
        public string Address { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Display(Name = "Email: ")]
        public string Email { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]
        [MinLength(11, ErrorMessage = "Contact must be in 11 numbers")]
        [MaxLength(11, ErrorMessage = "Contact must be in 11 numbers")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Contact must contain numbers only")]
        [Display(Name = "Contact: ")]
        public string Contact { set; get; }
        [Required(ErrorMessage = "Input Can Not Be Empty")]      
        [Display(Name = "Person Contact: ")]
        public string PersonContact { set; get; }
        public List<Supplier> Suppliers { set; get; }
    }
}

JesparWebApplication/JesparWebApplication/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Jespar.Model.Model;
using Jespar.BLL.BLL;
using JesparWebApplication.Models;
using AutoMapper;

namespace JesparWebApplication.Controllers
{
    public class SupplierController : Controller
    {

        SupplierManager _supplierManager = new SupplierManager();

        [HttpGet]
        public ActionResult Save()
        {
            SupplierViewModel supplierViewModel = new SupplierViewModel();


            supplierViewModel.Suppliers = _supplierManager.GetAll();

            return View(supplierViewModel);
        }
        [HttpPost]
        public ActionResult Save(SupplierViewModel supplierViewModel)
        {
            string message = "";

            //Supplier supplier = new Supplier();
            //supplier.Code = supplierViewModel.Code;
            //supplier.Name = supplierViewModel.Name;
            //supplier.Address = supplierViewModel.Address;
            //supplier.Email = supplierViewModel.Email;
            //supplier.Contact = supplierViewModel.Contact;
            //supplier.LoyaltyPoint = supplierViewModel.LoyaltyPoint;

            Supplier supplier = Mapper.Map<Supplier>(supplierViewModel);


            List<Supplier> suppliers = _supplierManager.GetAll();
            suppliers = suppliers.Where(c => c.Code.Contains(supplierViewModel.Code)).ToList();
            string isExits = "";
            string codeExitsMessage = "";
            foreach (var aSupplier in suppliers)
            {
                isExits = aSupplier.Code;
            }


            if (ModelState.IsValid)
            {
                if (isExits == supplierViewModel.Code)
                {

                    codeExitsMessage = "this Code ALreasy Exits";
                    ViewBag.CodeExits = codeExitsMessage;
                    //return Content(codeExitsMessage);
                }
                else
                {

                    if (_supplierManager.Save(supplier))
                    {
                        message = "Supplier Data Save Successfully";
                    }
                    else
                    {
                        message = "Data Not Save ";
                    }

                }


            }
            else
            {
                message = "ModelState failed";
            }

            ViewBag.message = message;

            supplierViewModel.Suppliers = _supplierManager.GetAll();

            return View(supplierViewModel);
            //return RedirectToAction("Search");
        }
        [HttpGet]
        public ActionResult Search()
        {
            SupplierViewModel supplierViewModel = new SupplierViewModel();
            supplierViewModel.Suppliers = _supplierManager.GetAll();
            return View(supplierViewModel);
        }
        [HttpPost]
        public ActionResult Search(SupplierViewModel supplierViewModel)
        {
            List<Supplier> suppliers = _supplierManager.GetAll();
            if (supplierViewModel.Code != null)
            {
                suppliers = suppliers.Where(c => c.Code.Contains(supplierViewModel.Code)).ToList();
            }
            supplierViewModel.Suppliers = suppliers;
            //return View(supplierViewModel);
            return View(supplierViewModel);




        }
        ////[HttpGet]
        //public ActionResult Show()
        //{
        //    List<Supplier> aSuppliers = _supplierManager.GetAll();
        //    ViewBag.a = aSuppliers;
        //    return View();
        //}

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var supplier = _supplierManager.GetById(id);
            SupplierViewModel supplierViewModel = Mapper.Map<SupplierViewModel>(supplier);

            supplierViewModel.Suppliers = _supplierManager.GetAll();
            return View(supplierViewModel);
        }
        [HttpPost]
        public ActionResult Edit(SupplierViewModel supplierViewModel)
        {
            string message = "";

            if (ModelState.IsValid)
            {
                Supplier supplier = Mapper.Map<Supplier>(supplierViewModel);

                if (_supplierManager.Update(supplier))
                {
                    message = "Update SuccessFuly!!";
                }
                else
                {
                    message = "Not Updated";
                }

            }
            else
            {
                message = "Modelstate failed";
            }

            ViewBag.Message = message;
            supplierViewModel.Suppliers = _supplierManager.GetAll();

            //return View(supplierViewModel);

            return RedirectToAction("Search");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Supplier supplier = _supplierManager.GetById(id);
            string message = "";
            if (_supplierManager.Delete(id))
            {
                message = "Delete Succsessfully!!";
            }
            else
            {
                message = "Not delete ";
            }
            ViewBag.Message = message;

            return RedirectToAction("Search");
        }


    }
}

JesparWebApplication/JesparWebApplication/Views/Supplier/Edit.cshtml
@model JesparWebApplication.Models.SupplierViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@section Mystyle
    {
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

}


<div class="container">
    <div class="card">
        <div class="card-header mb-0">
            <b>SUPPLIER INFO</b>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <form method="post">

                    <div class="form-group row">
                        @*<label for="colFormLabel" class="col-sm-2 col-form-label">Code</label>*@

                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Code)</label>
                        <div class="col-sm-10">
                            @*<td class="form-control"> @Html.TextBox("Code")</td>*@
                            @*<input type="text" name="Code" class="form-control">*@

                            @Html.TextBoxFor(c => c.Code, Model.Code, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.Code)
                            <input type="hidden" name="id" value="@Model.Id" class="form-control">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Name)</label>
                        <div class="col-sm-10">

                            @Html.TextBoxFor(c => c.Name, Model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.Name)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Address)</label>
                        <div class="col-sm-10">
                            @Html.TextAreaFor(c => c.Address, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.Address)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Email)</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(c => c.Email, Model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.Email)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Contact)</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(c => c.Contact, Model.Contact, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.Contact)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.PersonContact)</label>
                        <div class="col-sm-10">
                            @Html.TextBoxFor(c => c.PersonContact, Model.PersonContact, new { @class = "form-control" })
                            @Html.ValidationMessageFor(c => c.PersonContact)
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabel" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-3">

                            <input type="submit" value="Update" class="form-control btn btn-sm btn-primary">
                        </div>
                    </div>

                </form>
                <br />
                <br />
                <br />
                <br />
                <footer class="blockquote-footer">

                    Enter Supplier Info <cite title="Source Title">Get Message here....</cite>
                    @if (ViewBag.Message != null)
                    {
                        <h4 class="text-center text-primary">  @ViewBag.Message</h4>
                    }
                </footer>
            </blockquote>
        </div>
        <br />
        <br />

        @*@{
            Html.RenderPartial("~/Views/Shared/Supplier/_SupplierDetails.cshtml", Model);
        }*@


    </div>
</div>

@section MyScript
    {
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

JesparWebApplication/JesparWebApplication/Views/Supplier/Save.cshtml
@model JesparWebApplication.Models.SupplierViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}

@section Mystyle
    {
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
        .btn {
            border: double;
        }
    </style>

}

@section Search{
    @* <button class="col-md-4 btn btn-light"><a href="@Url.Action("Search", "Supplier")">Display Supplier</a></button>*@

    <div class="input-group">

        <span class="notification-indicator notification-indicator-info notification-indicator-ripple"></span>
        <a href="@Url.Action("Search", "Supplier")"><i class="grid-icon mdi mdi-table-of-contents mdi-2x"></i></a>


       
        @*<span class="grid-tittle">Bitbucket</span>*@
        
  

    @*<button class="btn btn-outline-info" type="submit"></button>*@
    </div>
}

<div class="container">
    <div class="row">


        <div class="col-md-10">
            <div class="card">
                <div class="grid-header mb-0">

                    <div class="row">
                        <label class="col-md-8"><b>SUPPLIER INFO</b></label>


                    </div>
                </div>
                <div class="grid-body">
                    <blockquote class="blockquote mb-0">
                        <form method="post">

                            <div class="form-group row">
                                @*<label for="colFormLabel" class="col-sm-2 col-form-label">Code</label>*@

                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Code)</label>
                                <div class="col-sm-10">
                                    @*<td class="form-control"> @Html.TextBox("Code")</td>*@
                                    @*<input type="text" name="Code" class="form-control">*@

                                    @Html.TextBoxFor(c => c.Code, new { @class = "form-control" })

                                    @Html.ValidationMessageFor(c => c.Code)



                                    @if (ViewBag.CodeExits != null)
                                    {

                                        <p>@ViewBag.CodeExits</p>
                                    }
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Name)</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.Name)
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Address)</label>
                                <div class="col-sm-10">
                                    @Html.TextAreaFor(c => c.Address, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.Address)
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Email)</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(c => c.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.Email)
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.Contact)</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(c => c.Contact, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.Contact)
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-2 col-form-label">@Html.LabelFor(c => c.PersonContact)</label>
                                <div class="col-sm-10">
                                    @Html.TextBoxFor(c => c.PersonContact, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.PersonContact)
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="colFormLabel" class="col-sm-8 col-form-label"></label>
                                <div class="col-sm-4">

                                    <input type="submit" name="btnSave" value="Save" class="form-control btn btn-sm btn-primary">
                                </div>
                            </div>

                        </form>
                        <br />
                        <br />
                        <br />
                        <br />
                        <footer class="blockquote-footer">

                            Enter Supplier Info <cite title="Source Title">Get Message here....</cite>
                            @if (ViewBag.message != null)
                            {
                                <h4 class="text-center text-primary">  @ViewBag.message</h4>
                            }
                        </footer>
                    </blockquote>
                </div>



            </div>
        </div>
        <div class="Col-md-2">

        </div>
    </div>
    <hr />


    @*@section Search

            {
            <form action="#" class="t-header-search-box" method="post">
                <div class="input-group">
                    <input type="text" value="@Model.Code" class="form-control" id="inlineFormInputGroup" placeholder="Search" autocomplete="off">
                    <button class="btn btn-primary" type="submit"><i class="mdi mdi-arrow-right-thick"></i></button>
                </div>
            </form>
        }*@

    @*@{
            Html.RenderPartial("~/Views/Shared/Supplier/_SupplierDetails.cshtml", Model);
        }*@



</div>



@section MyScript
    {
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}






@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Save</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    </head>
    <body>



        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src="~/Scripts/jquery-3.3.1.min.js"></script>
        <script src="~/Scripts/jquery.validate.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    </body>
    </html>*@

JesparWebApplication/JesparWebApplication/Views/Supplier/Search.cshtml
@model JesparWebApplication.Models.SupplierViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


    <div class="container">

        <hr />
        

        @section Search{
            <form action="#" class="t-header-search-box" method="post">
                <div class="input-group">
                    <input type="text" name="Code" value="@Model.Code" class="form-control" id="inlineFormInputGroup" placeholder="Search" autocomplete="off">
                    <button class="btn btn-outline-info" type="submit"><i class="mdi mdi-arrow-right-thick"></i></button>
                </div>
            </form>

        }

        @{
            Html.RenderPartial("~/Views/Shared/Supplier/_SupplierDetails.cshtml", Model);
        }





        @*<form method="post">
            <div class="form-group row">
                <label for="colFormLabel" class="col-sm-2 col-form-label">Code</label>
                <div class="col-sm-10">
                    <input type="text" name="Code" value="@Model.Code" class="form-control">
                </div>
            </div>
            <div class="form-group row">
                <label for="colFormLabel" class="col-sm-2 col-form-label"></label>
                <div class="col-sm-10">
                    <input type="submit" name="btnSearch" class="form-control btn btn-outline-info" value="Search">
                </div>
            </div>
        </form>*@



    </div>